spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/openmoney?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: laurent
    password: azerty
  

  
security:
  require-ssl: false
server:
  port: 10080
